### ISSUE TITLE
last character in title is truncated

### ISSUE THREAD

**Issue by ncoder-1** [madhat2r/polybar-i3-window#1]
Hi,

For some reason, on some windows, the last character in the title is truncated.  For example, when opening Steam, it will display as "Stea" and when opening a terminal with zsh shell, it will display as "zs".  In other windows, such as a qutebrowser tab, the title is displayed correctly.  Maybe a newline issue?

Here's my config:

```
[module/i3-window]
type = custom/script
label = %output:0:50:...%
label-foreground = ${colors.primary}
tail = true

[module/primary-i3-window]
inherit = module/i3-window
exec = ~/.config/polybar/i3-window.py DP-0

[module/secondary-i3-window]
inherit = module/i3-window
exec = ~/.config/polybar/i3-window.py DP-2
```

Any suggestions?

**Comment by madhat2r** [comment]
@ncoder-1 Go ahead and give it a try. Fix pushed to master.
Thanks.

**Comment by ncoder-1** [comment]
Yep that worked, thanks!
